chollosite/chollo_cart/urls.py
from django.urls import path

from chollosite.chollo_cart import views

app_name = 'chollo_cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:product_id>?', views.remove_from_cart, name='remove_from_cart'),
    ]

chollosite/chollo_main/urls.py
from django.urls import path, include
from . import views

app_name = 'chollo_main'


urlpatterns = [
    # views
    path("", views.home, name='home'),

    # # login
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #
    # # PasswordChange
    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    #
    # # PasswordReset
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('password_reset/uidb64/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/complete/', auth_views.PasswordResetCompleteView(), name='password_reset_complete'),

    # the whole auth could be replaced with the following line
    path('', include('django.contrib.auth.urls')),

    # other urls
    path("product_list/", views.product_list, name='product_list'),
    path("product_list/<slug:category_slug>", views.product_list, name='product_list_by_category'),
    path("product_detail/<int:id>/<slug:slug>", views.product_details, name='product_detail'),
    path("register/", views.register, name='register'),
    # path("cart_details/", views.cart_details, name='cart_details'),
    path('edit/', views.edit, name='edit'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('search/', views.item_search, name='item_search'),

]

chollosite/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create')
]

chollosite/chollo_main/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return f"Profile of {self.user.username}"


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["name"])
            ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chollo_main:product_list_by_category',
                       args=[self.slug])


# Crating model for the Categories
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True)
    description = models.TextField(max_length=500)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=["id", "slug"]),
            models.Index(fields=["name"]),
            models.Index(fields=["-created"]),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chollo_main:product_detail',
                       args=[self.id, self.slug])

chollosite/chollo_main/forms.py
from django import forms
from django.contrib.auth.models import User

from chollosite.chollo_main.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already in use. ')
        return data


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError('Email already in use. ')
        return data


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']


class SearchForm(forms.Form):
    query = forms.CharField()

chollosite/chollo_main/views.py
import random
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.shortcuts import render, get_object_or_404
from chollosite.chollo_cart.forms import CartAddProductForm
from .models import Category, Product, Profile
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm, SearchForm



def home(request):
    categories = list(Category.objects.all())

    # Select six random categories
    random_category = random.sample(categories, k=6)

    # Select random product from the categories
    random_products = []
    for category in random_category:
        # Retrieve a random product from each catogory
        random_product = Product.objects.filter(category=category).order_by('?').first()
        random_products.append(random_product)

    return render(request, "chollo_main/index.html",
                  {'random_products': random_products})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, "chollo_main/product_list.html",
                  {'category': category,
                  'categories': categories,
                  'products': products})


def product_details(request, id, slug):
    product = get_object_or_404(Product, id=id,
                                slug=slug,
                                available=True
                                )
    cart_product_form = CartAddProductForm()
    return render(request,
                  "chollo_main/product.html",
                  {"product": product,
                   "cart_product_form": cart_product_form,
                   }
                  )


@login_required
def dashboard(request):
    return render(request, 'registration/login.html',
                  {'section': 'dashboard'})

#
# def cart_details(request):
#     return render(request, "chollo_main/cart-details.html")


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # create a new user object but avoid saving
            new_user = user_form.save(commit=False)
            # set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # save the user object
            new_user.save()
            # Create the user profile
            Profile.objects.create(user=new_user)
            return render(request, 'chollo_main/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'chollo_main/register.html', {'user_form': user_form})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.user)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')

        else: messages.error(request, "Error updating your profile")

    else:
        user_form = UserRegistrationForm(instance=request.user)
        profile_form = ProfileEditForm(
            instance=request.user.profile
        )

        return render(request, 'chollo_main/edit.html',
                      {'user_form': user_form, 'profile_form': profile_form})


def item_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('name', weight='A') + SearchVector('description', weight='B',  config='spanish')
            search_query = SearchQuery(query, config='spanish')
            products = Product.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3).order_by('-rank')
            results = products
    return render(request, 'chollo_main/search.html',
                  {'form': form, 'query': query, 'results': results})

chollosite/chollo_main/templates/chollo_main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link href="{% static "chollo_main/style.css" %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static "chollo_main/media/logo.png" %}" type="image/x-icon">
</head>
<body>
    <header id="det-head">
        <div id="logo">

            <a href="{% url "chollo_main:home" %}" class="header-page">
                <img src="{% static "chollo_main/media/logo.png" %}" alt="logo">
            </a>

        </div>
        <div id="header-pages">
            <ul class="header-ul">
                <li><a href="{% url "chollo_main:product_list" %}" class="header-page">Collection</a></li>
                <li><a href="" class="header-page">Catalog</a></li>
                <li><a href="" class="header-page">About Us</a></li>
                <li><a href="" class="header-page">Blog</a></li>
            </ul>
        </div>

        <div id="social-links" class="header-ul">
            <a href="">
                <img src="{% static "chollo_main/media/icon/search icon.svg" %}" alt="Search icon" class="social-link">
            </a>

            {% if request.user.is_authenticated %}
            <a href="{% url "chollo_main:logout" %}">
                <img src="{% static "chollo_main/media/icon/avatar.svg" %}" alt="Avatar icon" class="social-link"> Logout
            </a>

            {% else %}
            <a href="{% url "chollo_main:login" %}">
                <img src="{% static "chollo_main/media/icon/avatar.svg" %}" alt="Avatar icon" class="social-link"> Login
            </a>

            {% endif %}


            {% if messages %}
                <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
                </li>
                {% endfor %}
                </ul>
            {% endif %}

            <a href="">
                <img src="{% static "chollo_main/media/icon/favourites.svg" %}" alt="Favourites icon" class="social-link">
            </a>
        </div>
        <div id="mobile-menu">
            <img src="{% static "chollo_main/media/icon/2931181_lines_list_menu_checklist_navigation_icon - Copy - Copy (2) 1.svg" %}" alt="Menu button" class="m-s-l">
        </div>
    </header>

{% block body %}

{% endblock %}

{%  block foot %}
    <section id="newsletter">
        <div id="newsletter-text">
            <h2 id="nsl-heading">Join Our Newsletter</h2>
            <span id="nsl-p">Subscribe Now! for free and save 10% on your first purchase</span>
        </div>
        <div id="form-intake">
            <form action="mailto:info@chollo.com" method="post">
                <input type="email" placeholder="Enter your Email Address" id="emailfield"/>
                <input type="submit" value="Send" id="sendbutton">
            </form>
        </div>
    </section>
    <footer>
        <div id="footer-docl">
            <div class="footer-link-con">
                <ul class="footer-links">
                    <li><a href="" class="footer-link">Collection</a></li>
                    <li><a href="" class="footer-link">Catalog</a></li>
                    <li><a href="" class="footer-link">About Us</a></li>
                    <li><a href="" class="footer-link">Blog</a></li>
                </ul>
            </div>
            <div id="footer-social">
                <a href="" class="soc-icon">
                    <img src="{% static "chollo_main/media/icon/bx-envelope.svg" %}" alt="Email icon">
                </a>
                <a href="" class="soc-icon mobile-mvd">
                    <img src="{% static "chollo_main/media/icon/bxl-facebook.svg" %}" alt="Facebook icon">
                </a>
                <a href="" class="soc-icon">
                    <img src="{% static "chollo_main/media/icon/bxl-instagram.svg" %}" alt="Instagram icon">
                </a>
                <a href="" class="soc-icon mobile-mvd">
                    <img src="{% static "chollo_main/media/icon/bxs-phone.svg" %}" alt="Phone icon">
                </a>
                <a href="" class="soc-icon">
                    <img src="{% static "chollo_main/media/icon/bxl-twitter.svg" %}" alt="Twitter icon">
                </a>
            </div>
        </div>
        <hr id="top-line">
        <div id="footer-docs">
            <a href="">CUSTOMERS SERVICE AND TERMS</a>
            <a href="">MATERIALS & CARE</a>
            <a href="">PRIVACY POLICY</a>
        </div>
        <hr id="bottom-line">
    </footer>
{% endblock %}
</body>
</html>

chollosite/chollo_main/templates/chollo_main/cart-details.html
{% extends "chollo_main/base.html" %}
{% load static %}


{% block body %}

    <section id="nav-menu">

        <div id="div-nav-menu">
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
            Your cart:
            <a href="{% url "chollo_cart:cart_detail" %}">
            {{ total_items }} item{{ total_items|pluralize }},
            N{{ cart.get_total_price }}
            </a>
            {% elif not order %}
                Your cart is empty.
            {% endif %}
            {% endwith %}
        </div>

    </section>
    <section>
        <div id="loc-pay">
            <div id="locdiv" class="white">
                <img id="loc-icon" src="{% static "chollo_main/media/icon/heroicons-outline/location-icon.png" %}" alt="location icon">
                <form class="locpay-form" action="mailto:info@chollo.com" method="post">
                    <input type="email" placeholder="Enter delivery location" id="sel-location"/>
                </form>
            </div>
            <div id="paydiv" class="white">
                <img id="pay-icon" src="{% static "chollo_main/media/icon/heroicons-outline/payment-options.png" %}" alt="">
                <form class="locpay-form" action="mailto:info@chollo.com" method="post">
                    <input type="email" placeholder="Select payment method" id="payment-provider"/>
                </form>
                <img id="dropdown" src="{% static "chollo_main/media/icon/Vector 335dropdown.svg" %}" alt="">
            </div>
        </div>


    {% for item in cart %}
        {% with product=item.product %}

        <div class="white batch-two">
            <div class="batch-two-prod">
                <div class="bt-one">
                    <img class="bt-o-img" src="{% static "chollo_main/media/icon/heroicons-outline/store-icon.svg" %}" alt="">
                    <p class="bt-one-txt">
                        <span>Nnamdi's</span> Men Store
                    </p>
                    <img class="bt-o-clp" src="{% static "chollo_main/media/icon/heroicons-outline/clipboard.svg" %}" alt="">
                </div>

                <div class="bt-two">
                    <img class="bt-two-img" src="{{ product.image.url }}" alt="">
                    <div class="bt-two-txtgrp">
                        <div class="bt-two-title">
                            <p class="product-name">{{ product.name }}</p>
                        </div>

                        <form action="{% url "chollo_cart:add_to_cart" product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.override }}
                            <input type="submit" value="Update">
                            {% csrf_token %}
                        </form>

                        <p class="bt-two-price">UNIT PRICE: N{{ product.price }}</p>
                        <p class="bt-two-price">Price: N{{ item.total_price }}</p>
                    </div>
                    <form action="{% url "chollo_cart:remove_from_cart" product.id %}"
                        method="post">
                        <input type="submit" value="Remove">
                        {% csrf_token %}
                    </form>
                    <div class="c-quantity">
                        <div class="align-c redu-quan">
                            <img src="{% static "chollo_main/media/icon/Vector 615.svg" %}" alt="Reduce button">
                        </div>
                        <div class="quan-number">
                            <p class="qu-number">1</p>
                        </div>
                        <div class="align-c incr-quan">
                            <img src="{% static "chollo_main/media/icon/plus icon.svg" %}" alt="Add button">
                        </div>
                    </div>
                </div>
                <div class="bt-three">
                    <div class="bt-three-one">
                        <p><span class="black">Delivery: </span><span>Free Delivery</span></p>
                        <p><span class="black">Estimated Delivery: </span><span>after 24 hours</span></p>
                    </div>
                    <div class="bt-three-two">
                        <img src="{% static "chollo_main/media/icon/heroicons-outline/favourites shaded.svg" %}" alt="">
                    </div>
                </div>
            </div>
        </div>

            {% endwith %}
        {% endfor %}



        <div id="batch-three">
            <div id="summarydiv" class="white">
                <div id="sumtext">Summary</div>
                <div id="sump">
                    <p id="ticsmbx1" class="sump50">Total items cost</p>
                    <p id="ticsmbx2" class="sump50">Total shipping</p>
                    <p id="ticsmbx3">N {{ cart.get_total_price }}</p>
                    <p id="ticsmbx4">Free</p>
                </div>
            </div>
            <div id="summarybox" class="white">
                <p class="summbox32">Total</p>
                <h2 class="summbox32">NGN 12,000</h2>
            </div>
            <a href="{% url "orders:order_create" %}" >
            <div class="white" id="m-white">
                <button id="buy-now" class="btn place-o">Checkout</button>
            </div>
            </a>
        </div>
    </section>

{% endblock %}

chollosite/chollo_main/templates/chollo_main/index.html
{% extends "chollo_main/base.html" %}

{% load static %}

{% block body %}

    <section id="nav-menu">
        <div id="div-nav-menu" style="display: flex; justify-content: center;">
            <p>Welcome to Chollo! We bring the market <span style="color: var(--orange);">closer</span> to you. Enjoy <span style="color: var(--orange);">FREE</span> shipping on a product per week</p>
        </div>
    </section>
    <section id="landing-photo-cont">
        <div id="lpc-navbutton" style="display: none;">

        </div>
        <div id="lpc-verticalslider">
            <div class="lpc-vs-circle lpcvcfull"></div>
            <div class="lpc-vs-circle"></div>
            <div class="lpc-vs-circle"></div>
            <div class="lpc-vs-circle"></div>
        </div>
        <div id="lpc-lph1-cont">
            <div id="lpc-lph1">
                <h1 id="lph1">Bringing the market <span style="color: var(--orange); font-size: 64px;">closer</span> to you</h1>
                <a href="{% url 'chollo_main:product_list' %}"> <button id="lpcbtn" class="btn"> SHOP NOW </button> </a>
            </div>
        </div>
        <div id="lpc-navbutton-cont"> 
            <p>More</p>
            <img src="{% static "chollo_main/media/icon/rightarrowicon.svg" %}" alt="right arrow icon">
        </div>
    </section>
    <section id="feat-lp">
        <div class="ft-lp-cont">
            <div class="ftlp-img">
                <img src="{% static "chollo_main/media/icon/rocketlaunch.svg" %}" alt="rocket icon">
            </div>
            <div class="ftlp-txt">
                <p class="ftlp-main-txt">Free Shipping</p>
                <p class="ftlp-sup-txt">1 every week</p>
            </div>
        </div>
        <div class="ft-lp-cont">
            <div class="ftlp-img">
                <img src="{% static "chollo_main/media/icon/walleticon.svg" %}" alt="rocket icon">
            </div>
            <div class="ftlp-txt">
                <p class="ftlp-main-txt">Payment Method</p>
                <p class="ftlp-sup-txt">Online System</p>
            </div>
        </div>
        <div class="ft-lp-cont">
            <div class="ftlp-img">
                <img src="{% static "chollo_main/media/icon/recordcameraicon.svg" %}" alt="rocket icon">
            </div>
            <div class="ftlp-txt">
                <p class="ftlp-main-txt">Online Support</p>
                <p class="ftlp-sup-txt">Every 24 hours</p>
            </div>
        </div>
        <div class="ft-lp-cont">
            <div class="ftlp-img">
                <img src="{% static "chollo_main/media/icon/moneyicon.svg" %}" alt="rocket icon">
            </div>
            <div class="ftlp-txt">
                <p class="ftlp-main-txt">Money Guarantee</p>
                <p class="ftlp-sup-txt">7 days back</p>
            </div>
        </div>
        <div class="ft-lp-cont">
            <div class="ftlp-img">
                <img src="{% static "chollo_main/media/icon/recordcameraicon.svg" %}" alt="rocket icon">
            </div>
            <div class="ftlp-txt">
                <p class="ftlp-main-txt">100% Safe</p>
                <p class="ftlp-sup-txt">Secure</p>
            </div>
        </div>
    </section>


    <section id="shop-by-categories">
        <div id="sbc-details">
            <div id="sbcd-txt">
                <p>Shop by Categories</p>
                <div class="sbcline"></div>
            </div>
            <p id="sbcd-view-more">View More</p>
        </div>
        <div id="sbc-grid">
        {% for product in random_products %}
           <a href="{{ product.category.get_absolute_url }}">
            <div id="sbcg-grp">
                <div class="sbc-prod sbc-card">
                    <img src="{{product.image.url}}" alt="" class="sbc-grid-img">
                    <p class="sbc-grid-txt">{{ product.category.name }}</p>
                </div>
            </div>
           </a>
        {% endfor %}
        </div>
    </section>


    <section id="dealsoftheday">
        <div id="doddetail">
            <div class="sbcline"></div>
            <p>DEALS OF THE DAY</p>
        </div>
        <div id="dodcontent">
            <div class="dodc-item">
                <div class="dodc-item-img">
                    <img src="{% static "chollo_main/media/product-image/computer dod.png" %}" alt="Macbook photo">
                    <p class="new-tag">-35%</p>
                </div>
                <div class="dodc-item-details">
                    <div class="dodc-id-rating">
                        <img src="{% static "chollo_main/media/icon/Star 5.svg" %}" alt="Star rating image">
                        <p>4.5</p>
                    </div>
                    <h3 class="dodc-id-title">
                        HP LAPTOP PAVILLON X360
                    </h3>
                    <div class="dodc-id-price">
                        <p class="original-price">NGN 12,000</p>
                        <p class="discounted-price">NGN 8,000</p>
                    </div>
                    <div class="dodc-id-timer">
                        <div class="dodc-id-t-details">
                            <span class="dodc-idt-d">12</span> :
                            <span class="dodc-idt-d">50</span> :
                            <span class="dodc-idt-d">45</span>
                        </div>
                        <div class="dodc-id-t-static">
                            <p class="dodc-idt-s">HRS</p>
                            <p class="dodc-idt-s">MINS</p>
                            <p class="dodc-idt-s">SEC</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dodc-item">
                <div class="dodc-item-img">
                    <img src="{% static "chollo_main/media/product-image/nikedod.png" %}" alt="Nike sneakers photo">
                    <p class="new-tag">-35%</p>
                </div>
                <div class="dodc-item-details">
                    <div class="dodc-id-rating">
                        <img src="{% static "chollo_main/media/icon/Star 5.svg" %}" alt="Star rating image">
                        <p>4.5</p>
                    </div>
                    <h3 class="dodc-id-title">
                        NEW NIKE ULTRA BOOST
                    </h3>
                    <div class="dodc-id-price">
                        <p class="original-price">NGN 12,000</p>
                        <p class="discounted-price">NGN 8,000</p>
                    </div>
                    <div class="dodc-id-timer">
                        <div class="dodc-id-t-details">
                            <span class="dodc-idt-d">12</span> :
                            <span class="dodc-idt-d">50</span> :
                            <span class="dodc-idt-d">45</span>
                        </div>
                        <div class="dodc-id-t-static">
                            <p class="dodc-idt-s">HRS</p>
                            <p class="dodc-idt-s">MINS</p>
                            <p class="dodc-idt-s">SEC</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="suggestions">
        <div id="lpc-horizontalslider">
            <div class="lpc-vs-circle lpcvcfull"></div>
            <div class="lpc-vs-circle"></div>
            <div class="lpc-vs-circle"></div>
            <div class="lpc-vs-circle"></div>
        </div>
        <div id="sugg-details-cont">
            <div id="sugg-1st-cont">
                <img src="{% static "chollo_main/media/logo.png" %}" alt="Chollo logo">
                <div id="sugg-cam-text">
                    <p id="sct-bigtext">Professional Camera Zoom</p>
                    <p id="sct-smalltext">Upgrade your shopping</p>
                </div>
                <div id="sugg-cam-flex">
                    <div id="sugg-cam-cont">
                        <div class="sugg-cam-border top-left"></div>
                        <div class="sugg-cam-border bottom-left"></div>
                        <div class="sugg-cam-border top-right"></div>
                        <div class="sugg-cam-border bottom-right"></div>
                        <img src="{% static "chollo_main/media/icon/camera.png" %}" alt="Camera icon">
                    </div>
                </div>
                <button id="lpcbtn" class="btn">EXPLORE NOW!</button>
            </div>
            <div id="sugg-2nd-cont">
                <a href="{% url 'chollo_main:product_list' %}"> <img src="{% static "chollo_main/media/SAVE_20230525_083734.png" %}" alt="Chollo promotional flyer"></a>
            </div>
            <div id="sugg-3rd-cont">
                <div id="sugg-3con-details">
                    <div id="sugg-3cond-cont">
                        <p id="sugg-3con-maintxt">Apple</p>
                        <div id="sugg-3con-txtcont">
                            <p id="sugg-3con-2ndmaintext">New iPad 13 Pro</p>
                            <p id="sugg-3con-3rdmaintext">Available</p>
                        </div>
                    </div>
                </div>
                <img src="{% static "chollo_main/media/product-image/ipad.png" %}" alt="iPad">
            </div>
        </div>
    </section>

{% endblock %}

chollosite/chollo_main/templates/chollo_main/product_list.html
{% extends "chollo_main/base.html" %}
{% load static %}

{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block body %}
<div id="sidebar">
<h3>Categories</h3>

<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url "chollo_main:product_list" %}">All</a>
</li>


    {% for c in categories %}
<li {% if category.slug == c.slug %}class="selected"
{% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}


</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Products
{% endif %}</h1>
{% for product in products %}
<div class="item">
<a href="{{ product.get_absolute_url }}">
<img src="{% if product.image %}{{ product.image.url }}{% else %}{%static "img/no_image.png" %}{% endif %}">
</a>
<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
<br>
${{ product.price }}
</div>
{% endfor %}
</div>
{% endblock %}

chollosite/chollo_main/templates/chollo_main/search.html
{% extends "chollo_main/base.html" %}
{% block body %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
{% with results.count as total_results %}
Found {{ total_results }} result{{ total_results|pluralize }}
{% endwith %}
</h3>
{% for product in results %}
<h4>
<a href="{{ product.get_absolute_url }}">
{{ product.name }}
</a>
</h4>
{{ product.body }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url "chollo_main:item_search" %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form method="get">
{{ form.as_p }}
<input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}